### ISSUE TITLE
Item header 

### ISSUE THREAD

**Issue by G1K** [sokolnikov911/yandex-turbo-pages-php5#2]
Может быть добавить пару методов чтобы добавлять заголовок страницы и главное изображение?

```
<header>
<figure>
<img src="" />
</figure>
<h1></h1>
</header>
```

**Comment by sokolnikov911** [comment]
**G1K**, я думал об этом. Но тут возникает несколько вопросов.

1. Если делать отдельный класс (не метод) для работы с заголовком, то надо делать и класс для работы с телом, чтобы полностью закрыть вопрос с наполнением turbo:content.
2. Если же делать класс для работы с телом, то надо решить каким он должен быть. Есть несколько вариантов:
а) делать методы для генерирования и добавления в тело каждой разрешенной html-сущности: a, ul, li, b, etc. (мало вероятно, что кому-то такой способ пригодится);
б) т.к. многие для создания страницы используют wysiwyg-редактор, и мало кто для турбо-страниц будет отдельно генерировать контент, поэтому, возможно, имеет смысл генерировать тело принимая пользовательский html, и, вырезая из него всё, что не разрешено спецификацией турбо-страниц (только надо думать что и как вырезать. Где-то достаточно пострипать теги, а где-то надо будет что-то решать с контентом, например с таблицами, цитатами, дивами и спанами, и т.д.); 
в) для тех, кто использует для создания и форматирования контента bbcode или markdown, сделать преобразователи в html, то, что можно преобразовать, остальное откидывать (опять же думать что и как преобразовывать и что откидывать).

Так вот пока я не придумал ответы на эти вопросы, я решил вообще не трогать область контента, и остановиться только на разметке фида. 

Какие у тебя есть мысли по этому поводу?

**Comment by G1K** [comment]
Идей особо нет, особенно по таблицам.
Этот момент уже преобразовывать пока универсально не вижу смысла тк нет примеров хороших преобразований вручную.
На счет BB и Markdown : Полезно, но наверное данный формат на первом этапе не стоит подключать. Просто для типа контент сделать интерфейс и по умолчанию подключать обработчик html , если другого не указано. Потом допилить реализацию для markdown.


По поводу wysiwyg , да скорей всего никто отказываться не будет, но валидатор яндекса не особо ругается на лишние теги (div с style) , а просто тупо вырезает их, если это не картинка и наверное другие типы (видео и тп).
Наверное хорошо было бы прикрутить htmlpurifier чтобы им вырезать все кроме разрешенных тегов.
Потом сделать пару регулярок ( замена : img без figure , видео iframe типа youtube )
Заменять наверно неплохо было бы через реплейс с коллбеком , чтобы можно было бы сделать проверку на 30 изображений в итеме. 

Пока вот такие идеи.

**Comment by sokolnikov911** [comment]
Добавил генератор хедера [https://github.com/sokolnikov911/yandex-turbo-pages-php5/commit/4a925c45c8529195a56bd0785b8678656d6114c1](https://github.com/sokolnikov911/yandex-turbo-pages-php5/commit/4a925c45c8529195a56bd0785b8678656d6114c1). Над генератором остального контента надо еще думать.
